---
# handlers file for ansible-role-pgbackrest
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: systemctl daemon-reload
  when:
    - ansible_service_mgr == 'systemd'

- name: Enable full backup timer
  ansible.builtin.systemd:
    name: "{{ pgbackrest_systemd_timer_name }}-full.timer"
    enabled: true
    state: started
  listen: systemctl enable pgbackrest-backup-full.timer
  when:
    - ansible_service_mgr == 'systemd'

- name: Enable differential backup timer
  ansible.builtin.systemd:
    name: "{{ pgbackrest_systemd_timer_name }}-diff.timer"
    enabled: true
    state: started
  listen: systemctl enable pgbackrest-backup-diff.timer
  when:
    - ansible_service_mgr == 'systemd'

- name: Enable incremental backup timer
  ansible.builtin.systemd:
    name: "{{ pgbackrest_systemd_timer_name }}-incr.timer"
    enabled: true
    state: started
  listen: systemctl enable pgbackrest-backup-incr.timer
  when:
    - ansible_service_mgr == 'systemd'
