---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include ansible-role-pgbackrest"
      ansible.builtin.include_role:
        name: "dudefellah.pgbackrest"
      tags:
        - molecule-converge-test
